### ISSUE TITLE
[BUG] surf_lint_rules. При локальном изменениии правил dart_code_metrics отваливается order элементов в классе

### ISSUE THREAD

**Issue by plastb1r** [surfstudio/SurfGear#271]
При отключении правил в своем analysis_options.yaml, например:

```
dart_code_metrics:
  rules:
    avoid-returning-widgets: false
```

Отключаются правила ordering.

Чтобы решить эту проблему приходится дублировать правила из библиотеки:

```
dart_code_metrics:
  rules:
    avoid-returning-widgets: false
    member-ordering-extended: 
      alphabetize: false
      order:
        - public-static-const-fields
        - private-static-const-fields
        - public-static-final-fields
        - private-static-final-fields
        - public-static-fields
        - private-static-fields
        - public-final-fields
        - private-final-fields
        - public-fields
        - public-getters-setters
        - private-fields
        - private-getters-setters
        - constructors
        - named-constructors
        - factory-constructors
        - overridden-methods
        - public-static-methods
        - public-methods
        - protected-methods
        - private-static-methods
        - private-methods
```
